#This will be integration for devlopement environments image will be test and push to docker registry (Test -> Build -> DockerHub)
name: recipe app api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
     

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Test and Lint
      run: |
        sudo apt-get install python3-dev libffi-dev gcc libc-dev make
        sudo docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
   
      
    - uses: actions/checkout@v2.3.2
      name: Build and Push

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: inderpalr/recipe-app-api-devops
        tags: v1
        registry: registry.hub.docker.com
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
