name: recipe app api (CI-test)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test and build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Test and Lint
      run: |
        sudo docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test && flake8"
   
      
    - uses: actions/checkout@v2.3.2
      name: Build and Push

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: inderpalr/recipe-app-api-devops
        tags: v1, latest
        registry: registry-url.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
